/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/coffee_mug.glb -d 
Author: vojtaklemperer (https://sketchfab.com/vojtaklemperer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ikea-mug-with-a-spoon-ad64f06cebb846b0b798cc26c78cacf2
Title: IKEA mug with a spoon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rustic_mug.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.spoon_mug_spoon_0.geometry} material={materials.mug_spoon} position={[-0.45, 4.737, 0.999]} rotation={[0.865, -0.301, 1.932]} scale={100} />
      <mesh geometry={nodes.mug_mug_spoon_0.geometry} material={materials.mug_spoon} position={[0, 8.014, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/rustic_mug.glb')
